server:
    port: 8022
spring:
    application:
        name: rabbitmq-consumer
    rabbitmq:
        host: 192.168.88.129
        port: 5672
        username: admin
        password: admin
        prefetch: 0
        listener:
            direct:
                acknowledge-mode: auto
            simple:
                acknowledge-mode: auto

properties:
    queue:
        insure:
            add: insureadd
            update: insureupdate
            del: insuredel
        money:
            add: moneyadd
            update: moneyupdate
            del: moneydel
        financing:
            add: financingadd
            update: financingupdate
            del: financingdel